name: API Diff
on:
  pull_request:
    branches:
      - main

jobs:
  go-apidiff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 'stable'
      - uses: joelanford/go-apidiff@v0.6.0
