name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '1.20'
      - name: Coverage
        run: go test -v -covermode=count -coverprofile=coverage.txt ./...
      - name: Codecov
        uses: codecov/codecov-action@v3
